id: P33A75A5A
initial_creation_type: input
source_metadata:
  title: Ten Royal Sūtras
  language: en
  description: 'A collection related to the ten royal sūtras or ten sūtras of the
    king (rgyal po''i mdo bcu), which are said to have been translated upon the advice
    of Padmasambhava for Emperor Tri Songdetsen''s daily recitation:'
  volume:
    86fc8dd9443242b3aa90b0dd873f3814:
      title: Outline of the Ten Royal Sūtras
      parent: Outlines
    62ca8b7369de46358c3d816cc338529d:
      title: The Bodhisattva’s Confession of Downfalls (Nyingma Version)
      parent: Sūtras
    48574814bf38478a80f51658bb6c3eb8:
      title: The Dhāraṇī of Stream of Wealth (Vasudhārā)
      parent: Sūtras
    07efec1fbe5f46adb9d72ff7155c53de:
      title: The Heart of the Transcendent Perfection of Wisdom
      parent: Sūtras
    6017c79fb948400db597533b4ee0a3a5:
      title: 'The King of Aspiration Prayers: Samantabhadra''s “Aspiration to Good
        Actions” (Zangchö Mönlam)'
      parent: Sūtras
    372f849aac504444a00691de7519cf1f:
      title: The Noble Dhāraṇī of The Supreme Accomplishment of Sitātapatrā Born from
        the Tathāgata’s Uṣṇīṣa, the Great Invincible Dispeller
      parent: Sūtras
    e7e8b43aa50f454dbfdb653c3d4091a5:
      title: The Noble Incantation entitled ‘The Rituals for the Blue-Clad Vajrapāṇi’
      parent: Sūtras
    2e9b22f9faf5444a8c49fc781d931c4e:
      title: The Noble Mahāyāna Sūtra entitled The Wisdom of the Hour of Death
      parent: Sūtras
    e483e68955f94b278c65d1f772696d81:
      title: The Perfection of Wisdom, Mother of All Tathāgatas, ‘In One Syllable’
      parent: Sūtras
    0f9aeda4c0cf4a80b13f52f40f937087:
      title: The Sūtra of Boundless Life and Wisdom
      parent: Sūtras
    c3a0aab90cae4565bbe5db26f9711455:
      title: Vajravidāraṇa Dhāraṇī (Nyingma Version)
      parent: Sūtras
created_at: '2022-03-01T06:06:38.011034'
last_modified_at: '2022-03-01T06:06:38.011040'
